# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test-build

on:
  push:
    branches: [ "main" ,"dev"]
  pull_request:
    branches: [ "main" ]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: ./pvsz-api/package-lock.json
    - name: Install dependencies
      working-directory: ./pvsz-api
      run: npm install
    - name: Install newman
      working-directory: ./pvsz-api
      run:  |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    
    - name: Make Directory for results
      run: mkdir -p testResults
      working-directory: ./pvsz-api
    - name: Run POSTMAN collection
      working-directory: ./pvsz-api
      run: |
        npm run dev
        newman run test/pvsz-testing.postman_collection.json --environment test/PVSZ.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
    - name: Output the run Details
      uses: actions/upload-artifact@v2
      with: 
       name: RunReports
       path: /pvsz-api/testResults
